<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [1]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'


In [3]:
greeting('superman')

'Hello superman!'

In [7]:
greeting(name="Super Man")

'Hello Super Man!'

In [5]:
greeting("batman")   # remember, case sensitive

'Hello batman!'

In [6]:
greeting("Batman")

'Hello Batman! So, nice to meet you!'

In [8]:
greet=greeting(name='Super Man')
print(greet)

Hello Super Man!


In [9]:
print(greeting(name='Super Man'))

Hello Super Man!


In [10]:
def basic_stats(numbers):           # what does this line do?
    np_numbers=np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()

In [11]:
list_min, list_max, list_mean = basic_stats([1, 2, 3, 4, 5])

### 1.2 Named functions that don’t return

In [12]:
#print() is an example of a function that does something but does not return a value


### 1.3 Anonymous functions

In [ ]:
def my_short_function(name):
    return f"Hello {name}!"

In [13]:
my_short_function = lambda name: f"Hello {name}!"    # suitable for short one-liners

In [14]:
my_short_function(name="Super Man")                  #can accept a single argument "name"

'Hello Super Man!'

In [15]:
numbers=[[9, 0, 10],             # 'sorted' is an inbuilt python function
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]

sorted(numbers)                         # Sort by comparing the default key 
                                        # (i.e. the 1st element) 

[[0, 9, 19],
 [1, 8, 18],
 [2, 7, 17],
 [3, 6, 16],
 [4, 5, 15],
 [5, 4, 14],
 [6, 3, 13],
 [7, 2, 12],
 [8, 1, 11],
 [9, 0, 10]]

In [18]:
def short(x):                   # for most functions, you have to define them first before using them
    return x[1]

In [19]:
sorted(numbers, key=short)     # these are the two lines that you would have to write if "lambda" didn't exist

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

In [16]:
sorted(numbers, key=lambda x: x[1])     # Sort by comparing a custom key
                                        # that uses the 2nd element
# lambda allows you to define and use the function immediately, but since it's not defined, you can't use it again later on
# because the function is not named(single use only)

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

In [20]:
sorted(numbers, key=lambda x: sum(x))   # Sort by comparing a custom key
                                        # that uses the sum of the elements

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

### 1.4 Optional arguments

In [25]:
def greeting(name='no one'):          # assigns a default value to the argument when it would normally be just "name"
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'


In [26]:
greeting("Batman")

'Hello Batman! So, nice to meet you!'

In [27]:
greeting()

'Hello no one!'

In [28]:
print('I', 'am', 'Batman!')                 # Just for comparison
#> I am Batman!
print('I', 'am', 'Batman!', sep='---')   # 'sep' inserts a string between values, default is a space
#> I---am---Batman!

I am Batman!
I---am---Batman!


## 2 The importance of functions?

### 2.1 An argument for functions

1. Abstraction of details: certain processes can be compartmentalised so that it is easier to focus on other things
2. Allows you to reuse a chunk of code without having to copy and paste it many times
3. Allows code to be more easily maintained because you only have to change it at one point(the definition of the function)

### 2.2 A word of caution

Functions can be abused. Some ways include:
1. trying to do too much within one function
2. having too many functions, making things very messy

## Exercise 1 :  Do you know why?

In [29]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    return f'Hello {name}!'

# why does this code work despite not having an 'else' function?

because if the 'if' condition is not 

## Exercise 2 :  Calculator functions

In [77]:
def add(x,y):
    return x+y


In [78]:
def subtract(x,y):
    return x-y

In [79]:
def multiply(x,y):
    return x*y

In [80]:
def divide(x,y):                       # still can't figure out how to use 'exit()' to exclude the zero
    if y.all()==0:
        return "error"
    return x/y

In [81]:
x=np.array([36, 34, 44, 76, 27, 100])
y=np.array([64, 66, 56, 24, 73, 0])

In [82]:
add(x,y)

array([100, 100, 100, 100, 100, 100])

In [83]:
subtract(x,y)

array([-28, -32, -12,  52, -46, 100])

In [84]:
subtract(x,y, key=lambda a: a[3])         # How do I add the lambda function to retrieve the 3rd variable, for instance?
                                          # how do I add a function to retrieve all the positive values(4th element)

TypeError: subtract() got an unexpected keyword argument 'key'

In [85]:
multiply(x,y)

array([2304, 2244, 2464, 1824, 1971,    0])

In [86]:
divide(x,y)

'error'

In [87]:
arr_1 = np.array([0,1,2,3,4])             #illustration on what 'all()' and 'any()' does
arr_2 = np.array([1,2,3,4,5])
arr_3 = np.array([0,0,0,0,0])

print(arr_1.all(), arr_1.any())
print(arr_2.all(), arr_2.any())
print(arr_3.all(), arr_3.any())

False True
True True
False False


## Exercise 3 :  max_info() with NumPy

In [ ]:



# Your solution here


