<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [1]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

x = np_array

In [2]:
x[0]

'a1'

In [3]:
x[-10]

'a1'

In [4]:
x[-1]

'j10'

In [7]:
x[0:3] #index 0 to 2, gives 3-0=3 elements

array(['a1', 'b2', 'c3'], dtype='<U3')

In [8]:
x[1:6] #index 1 to 5, gives 6-1=5 elements

array(['b2', 'c3', 'd4', 'e5', 'f6'], dtype='<U3')

In [9]:
x[1:6:2] # index 1 to 5 in steps of 2, gives every other element of 6-1=5 elements

array(['b2', 'd4', 'f6'], dtype='<U3')

In [10]:
x[5:] #index 5 to the end, gives len(x)-5 number of elements

array(['f6', 'g7', 'h8', 'i9', 'j10'], dtype='<U3')

In [12]:
x[:5] # index 0 to 5, gives 5-0=5 elements

array(['a1', 'b2', 'c3', 'd4', 'e5'], dtype='<U3')

In [16]:
x[5:2:-1] #index 5 to 3, in reverse

array(['f6', 'e5', 'd4'], dtype='<U3')

In [17]:
x[5:2] # why does this not work?

array([], dtype='<U3')

In [18]:
x[::-1] #reverses the list

array(['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1'],
      dtype='<U3')

### 1.2 Subsetting by masking (Arrays only)

In [19]:

np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
print(my_mask) #python gives you a true/false answer depending on what you put in your mask

[False False False  True  True  True  True  True  True  True]


In [20]:
np_array[my_mask] # this asks python to show only the elements that match 'true'

array([ 4,  5,  6,  7,  8,  9, 10])

In [ ]:
#subsetting my masking only works for numpy arrays

In [21]:
np_array[np_array > 3] #efficient way of arriving at this output

array([ 4,  5,  6,  7,  8,  9, 10])

In [22]:
np_array[~(np_array > 3)]                         # '~' means 'NOT', it's a Bitwise NOT operator

array([1, 2, 3])

In [23]:
np_array[(np_array > 3) & (np_array < 8)]         # '&' means 'AND'

array([4, 5, 6, 7])

In [25]:
np_array[(np_array < 3) | (np_array > 8)]         # '|' means 'OR'

array([ 1,  2,  9, 10])

In [26]:
#you MUST use the bitwise operators when combining masks with Numpy

### 1.3 Indexing & Slicing 2D Lists

In [27]:

py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

In [28]:
py_list_2d[3]        # What is at position 4 (index 3)?

[4, 'D']

In [29]:
py_list_2d[3][0]     # FIRST element at position 4 (index 3)

4

In [30]:
py_list_2d[:3]  #elements from position 0 to position 2

[[1, 'A'], [2, 'B'], [3, 'C']]

In [31]:
py_list_2d[:3][0] # elements from position 0 to position 2, take the first element

[1, 'A']

In [33]:
py_list_2d[3:6]      #elements from position 3 to position 5

[[4, 'D'], [5, 'E'], [6, 'F']]

In [34]:
py_list_2d[3:6][0]     #elements from position 3 to position 5, take the first element

[4, 'D']

### 1.4 Indexing & Slicing 2D Arrays

In [35]:
# recall that arrays use normal brackets, lists use square brackets
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])

In [36]:
np_array_2d[3]       # What is at position 4 (index 3)?

array(['4', 'D'], dtype='<U11')

In [38]:
np_array_2d[3, 0]    # FIRST element at position 4 (index 3). note how only one set of square brackets are used for arrays

'4'

In [40]:
np_array_2d[:3]     # Positions 1 to 3(index 2)

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U11')

In [41]:
np_array_2d[:3, 0]    # positions 1 to 3(index 2), take the first element of each element

array(['1', '2', '3'], dtype='<U11')

In [42]:
np_array_2d[3:6, 0]    #positions 3 to 5, take the first element of each element

array(['4', '5', '6'], dtype='<U11')

In [43]:
np_array_2d[:, 0]       #':' gives you everything, take the first element of each element

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U11')

### 1.5 Growing lists

In [44]:

x=[1]*10
x               # I am lazy to type print()
                # Let Jupyter do the hard work.

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [45]:
x=[1]             # making a list by adding one element at a time
x= x + [2]
x= x + [3]
x= x + [4]
x

[1, 2, 3, 4]

In [46]:
x=[1]       # alternative way of making the same list
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [47]:
x=[1]                    # adding multiple elements at one go
x+= [2, 3, 4]
x

[1, 2, 3, 4]

In [48]:
x=[1]                   # adding the elements before the list, instead of after(conventionally)
x= [2, 3, 4] + x 
x

[2, 3, 4, 1]

In [49]:
x=[1]                         # another way of appending(adding) elements
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

## 2 Some loose ends

### 2.1 Tuples

In [50]:
# tuples are similar to lists, except that they use normal brackets and cannot be changed
a=(1, 2, 3)     # Define tuple

In [51]:
print(a[0])    # Access the first element of the tuple

1


In [52]:
# The following will NOT work because you cannot change the data
a[0]=-1
a[0] += [10]

TypeError: 'tuple' object does not support item assignment

### 2.2 Be VERY careful when copying

In [53]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!


In [54]:
x=[1, 2, 3]              # correct way to copy lists
y=x.copy()
z=x.copy()

## Exercise 1 :  Total recall?

Subsetting: Selecting data from a set of data

Indexing: selecting a specific element(s) from a set of data

Slicing: Obtaining a range of data from one part of your dataset

Masking: A type of rule that allows you to only show you certain elements from the dataset that fulfil that rule




## Exercise 2 :  Show me the ‘odd’ letters

In [56]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])



In [57]:
np_array_2d[:,0]          # show only the first elements of everything

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U11')

In [89]:
y = np_array_2d[:,0]      # assigning y 

In [90]:
y=y.astype(int)            # changing the numbers from string type to integer type

In [91]:
list(numbers.astype(int))         #this line allows you to check that the string type has been changed to integer type

[1, 3, 2, 4, 5, 7, 6, 8, 10, 9]

In [92]:
y%2                        #divide and give the remainder

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1], dtype=int32)

In [95]:
my_mask = y%2==1           # assign mask, true=remainder is 1

In [96]:
print(my_mask)             

[ True  True False False  True  True False False False  True]


In [97]:
y[my_mask]                # apply the mask to y

array([1, 3, 5, 7, 9])

In [98]:
np_array_2d[my_mask]         # apply the mask to the original list

array([['1', 'A'],
       ['3', 'C'],
       ['5', 'E'],
       ['7', 'G'],
       ['9', 'I']], dtype='<U11')

In [99]:
np_array_2d[my_mask][:,1]      # apply the mask to the original list, show all the second elements

array(['A', 'C', 'E', 'G', 'I'], dtype='<U11')