<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [2]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"] #python lists
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [3]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"]) #numpy arrays
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [6]:
np_super_names = np.array(py_super_names)    # making use of what you already keyed in in the python lists
np_real_names = np.array(py_real_names)

In [4]:
superhero_info = {"Natasha Romanoff": "Black Widow", #dictionaries
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

### 1.2 Accessing data from a list (or array)

In [11]:
print(py_real_names[0]) # the number 0 retrieves the first element
print(py_super_names[0])
print(py_super_names[2]) #requires knowledge on size of list
print(py_super_names[-1]) #reverse indexing: immediately retrieves the last element

Natasha Romanoff
Black Widow
Doctor Strange
Doctor Strange


### 1.3 Accessing data from a dictionary

In [8]:
# key:value
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

print(superhero_info["Natasha Romanoff"])

Black Widow


In [9]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [10]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

In [11]:
print(list(superhero_info.values()).index("Black Widow"))            # This line tells me the position of the value in the dic
print(list(superhero_info.keys()))                               # this line gives me a list of all the keys

0
['Natasha Romanoff', 'Tony Stark', 'Stephen Strange']


In [28]:
list(superhero_info.keys())[0]           # list first, then square bracket for the index

'Natasha Romanoff'

### 1.4 Higher dimensional lists

In [2]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'], #for python lists, you can use 2D lists to store data sets that are
                     ['Tony Stark', 'Iron Man'], # lists themselves(such as coordinates)
                     ['Stephen Strange', 'Doctor Strange']]

## 2 Lists vs. Arrays

### 2.1 Size

In [12]:

py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array
        
len(py_list_2d) #len function counts the number of elements in a list

10

In [13]:
len(py_list_2d) # does this mean that once I convert the list into an array, python no longer recognises the list?

10

In [14]:
len(np_array_2d)

10

In [21]:
np_array_2d.shape #note that shape has no brackets, because it is not a function.
# it is a property or attribute of the numpy array
#output shows 10 elements and 2 dimensions
#Question: are there 3,4 or 5D lists or more?

(10, 2)

### 2.2 Arrays are fussy about type

In [5]:
py_list = [1, 1.5, 'A']
np.array(py_list) # note how the numbers are changed to string with the addition of the inverted commas
# This shows that numpy arrays only tolerate a single type

array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [8]:

py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [ ]:
py_list + 10        # won't work for lists

In [11]:
np_array + 10 # works for arrays

array([11, 12, 13, 14, 15])

In [12]:
np_array / 2

array([0.5, 1. , 1.5, 2. , 2.5])

### 2.4 Adding another list

In [16]:

py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1) #again, making use of a list to create a numpy array
np_array_2 = np.array(py_list_2) 

In [17]:
py_list_1 + py_list_2    # adding lists to each other merely places the numbers next to each other

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [18]:
np_array_1 + np_array_2    # adding arrays to each other adds the actual values together in sequence(1st+1st, 2nd+2nd...)

array([11, 22, 33, 44, 55])

In [19]:
np_array_1 + 2.0

array([3., 4., 5., 6., 7.])

In [20]:
py_list_1 + 2.0

TypeError: can only concatenate list (not "float") to list

### 2.5 Multiplying by a Number

In [21]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [22]:
py_list*2    # lists will literally list all the numbers, twice

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [23]:
np_array*2    # arrays will multiply the actual values of the numbers inside

array([ 2,  4,  6,  8, 10])

In [27]:
sort(py_list*2)

NameError: name 'sort' is not defined

### 2.6 Squaring

In [20]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [22]:
py_list**2                      # Won't work, you can't square a list

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [24]:
np_array**2         # all the elements are squared

array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [25]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [26]:
py_list == 3     # What this question is asking is whether the value of the list is equal to 3

False

In [29]:
py_list == 1

False

In [31]:
py_list == 5

False

In [34]:
py_list == 1,2,3,4,5

(False, 2, 3, 4, 5)

In [33]:
np_array == 3  # checks if every value is equal to 3

array([False, False,  True, False, False])

In [35]:
np_array > 3  # checks if every value is more than 3

array([False, False, False,  True,  True])

### 2.8 Mathematics

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [36]:
sum(py_list)     # sum() is a base Python function, adds up all the numbers in the list

15

In [37]:
max(py_list)     # max() is a base Python function

5

In [38]:
min(py_list)     # min() is a base Python function

1

In [ ]:
py_list.sum()   # Won't work!

In [39]:
np_array.sum() # note that functions usually come after the variable name, which in this case is np_array 

15

In [40]:
np_array.mean()

3.0

In [41]:
np_array.max()

5

In [42]:
np_array.min() # in general, an operation on a list works on the entire list
# while an operation on an array works on all the individual elements of the array

1

## Exercise 1 :  Total recall?

1. Both are able to store data
2. *Data can be retrieved from both in the same manner, using indexing or reverse indexing*


1. Lists are capable of storing different types of data(eg string, numbers, integers) but arrays are only able to store one type of data
2. Mathematical operations are applied to the entire list when used on lists but are applied to every element when used on arrays
3. Unlike arrays, it is not possible to square a list or add up the elements in a list


3. A dictionary is a way to store data in a way that two elements are linked together, in the form of a 'key' and *'value'*


## Exercise 2 :  Index me

In [43]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
print(py_list[0])                    # Prints 'a1'
print(py_list[2])                    # Prints 'c3'
print(py_list[4])                    # Prints 'e5'
print(py_list[6])                    # Prints 'g7'
print(py_list[8])   # Prints 'i9'



a1
c3
e5
g7
i9


## Exercise 3 :  Capitalise Heros

In [50]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()                  

print(superhero_info['Tony Stark'])

print(superhero_info['Natasha Romanoff'].upper())
print(superhero_info['Stephen Strange'].upper())

# What is the faster way to capitalise all the superhero names without writing 999 lines if there are 999 superhero names?

IRON MAN
BLACK WIDOW
DOCTOR STRANGE


## Exercise 4 :  How many ones

In [1]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]                  

np_array = np.array(numbers)

In [2]:
np_array == 1   #try not to rename your functions with a name that contains a dot

array([False, False,  True, False, False,  True, False, False, False,
        True, False, False, False, False, False, False, False,  True,
        True, False, False, False, False, False, False, False, False,
       False,  True, False,  True, False, False, False, False, False,
        True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False])

In [3]:
sum(np_array == 1) #'true' is recognised as 1 and 'false' is recognised as 0 by the function sum()

9

In [ ]:
#there are 9 trues so the sum is 9